(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ad-redefinition-action (quote accept))
 '(auto-insert-directory "~/.emacs.d/auto-insert/" nil nil "Customized with use-package autoinsert")
 '(backup-directory-alist (quote (("." . "~/.emacs.d/backups"))))
 '(cider-repl-history-file "~/.emacs.d/cider-history" t nil "Customized with use-package cider")
 '(cider-repl-history-size 5000 t nil "Customized with use-package cider")
 '(cider-repl-pop-to-buffer-on-connect t t nil "Customized with use-package cider")
 '(cider-repl-result-prefix "; => " t nil "Customized with use-package cider")
 '(cider-repl-use-clojure-font-lock t t nil "Customized with use-package cider")
 '(cider-repl-use-pretty-printing nil t nil "Customized with use-package cider")
 '(cider-repl-wrap-history t t nil "Customized with use-package cider")
 '(cider-show-error-buffer nil t nil "Customized with use-package cider")
 '(column-number-mode t)
 '(company-backends
   (quote
    (company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
                  (company-dabbrev-code company-gtags company-keywords)
                  company-oddmuse company-dabbrev)))
 '(custom-safe-themes
   (quote
    ("3c83b3676d796422704082049fc38b6966bcad960f896669dfc21a7a37a748fa" "1436d643b98844555d56c59c74004eb158dc85fc55d2e7205f8d9b8c860e177f" default)))
 '(deft-default-extension "org" t)
 '(deft-extensions (quote ("org" "txt" "text" "md" "markdown")) t)
 '(deft-file-naming-rules
    (quote
     ((noslash . "-")
      (nospace . "-")
      (case-fn . downcase))) t)
 '(deft-org-mode-title-prefix t t)
 '(deft-use-filename-as-title nil t)
 '(deft-use-filter-string-for-filename t t)
 '(desktop-lazy-idle-delay 1 nil nil "Restore the rest of the buffers 1 seconds later")
 '(desktop-lazy-verbose nil nil nil "Be silent about lazily opening buffers")
 '(desktop-restore-eager 1 nil nil "Restore only the first buffer right away")
 '(easy-hugo-basedir "~/Personal/devel/zzamboni.org/zzamboni.org/" t nil "Customized with use-package easy-hugo")
 '(easy-hugo-previewtime "300" t nil "Customized with use-package easy-hugo")
 '(easy-hugo-url "http://zzamboni.org/" t nil "Customized with use-package easy-hugo")
 '(epa-file-select-keys (quote silent))
 '(gist-view-gist t t nil "Automatically open new gists in browser")
 '(global-visible-mark-mode t)
 '(helm-flx-for-helm-find-files t t nil "Customized with use-package helm-flx")
 '(helm-flx-for-helm-locate t t nil "Customized with use-package helm-flx")
 '(iedit-toggle-key-default [67108923] t)
 '(indent-tabs-mode nil)
 '(jiralib-url "https://jira.swisscom.com" nil nil "Customized with use-package org-jira")
 '(js-indent-level 2)
 '(kill-whole-line t)
 '(load-prefer-newer t)
 '(lua-indent-level 2)
 '(mac-command-modifier (quote meta))
 '(mac-option-modifier (quote alt))
 '(mac-right-option-modifier (quote super))
 '(mouse-yank-at-point t)
 '(ns-alternate-modifier (quote alt))
 '(ns-command-modifier (quote meta))
 '(ns-right-alternate-modifier (quote super))
 '(org-agenda-files
   (quote
    ("~/Work/work.org" "~/org/diary.org" "/Users/taazadi1/Dropbox/Personal/org/journal/2019/09/20190920.gpg" "/Users/taazadi1/Dropbox/Personal/org/journal/2019/09/20190917.gpg")))
 '(org-agenda-include-diary t)
 '(org-confirm-babel-evaluate nil nil nil "Customized with use-package org")
 '(org-crypt-key "diego@zzamboni.org")
 '(org-default-notes-file "~/Dropbox/org/notes.org" nil nil "Customized with use-package org")
 '(org-directory "~/Dropbox/Personal/org" nil nil "Customized with use-package org")
 '(org-entities-user
   (quote
    (("llangle" "\\llangle" t "&lang;&lang;" "<<" "<<" "《")
     ("rrangle" "\\rrangle" t "&rang;&rang;" ">>" ">>" "》"))))
 '(org-export-with-broken-links t)
 '(org-hide-emphasis-markers t nil nil "Customized with use-package org")
 '(org-hugo-use-code-for-kbd t)
 '(org-journal-date-format "%A, %Y-%m-%d")
 '(org-journal-dir "~/Dropbox/Personal/org/journal")
 '(org-journal-enable-agenda-integration t)
 '(org-journal-enable-encryption nil)
 '(org-journal-encrypt-journal t)
 '(org-journal-file-format "%Y/%m/%Y%m%d")
 '(org-latex-compiler "xelatex" nil nil "Customized with use-package ox-latex")
 '(org-latex-pdf-process
   (quote
    ("%latex -shell-escape -interaction nonstopmode -output-directory %o %f" "%latex -interaction nonstopmode -output-directory %o %f" "%latex -interaction nonstopmode -output-directory %o %f")) nil nil "Customized with use-package ox-latex")
 '(org-log-done t nil nil "Customized with use-package org")
 '(org-log-into-drawer t)
 '(org-mac-grab-Acrobat-app-p nil)
 '(org-mac-grab-devonthink-app-p nil)
 '(org-plantuml-jar-path "/usr/local/Cellar/plantuml/1.2019.9/libexec/plantuml.jar" nil nil "Customized with use-package ob-plantuml")
 '(org-reveal-note-key-char nil nil nil "Customized with use-package ox-reveal")
 '(org-reveal-root "file:///Users/taazadi1/.emacs.d/lisp/reveal.js" nil nil "Customized with use-package ox-reveal")
 '(org-src-fontify-natively t nil nil "Customized with use-package org")
 '(org-src-tab-acts-natively t nil nil "Customized with use-package org")
 '(org-startup-indented t nil nil "Customized with use-package org")
 '(org-tags-column 0)
 '(org-todo-keyword-faces
   (quote
    (("PROPOSAL" . "orange")
     ("[PROPOSAL]" . "orange")
     ("DRAFT" . "yellow")
     ("[DRAFT]" . "yellow")
     ("INPROGRESS" . "yellow")
     ("[INPROGRESS]" . "yellow")
     ("CANCELED" . "blue")
     ("[CANCELED]" . "blue"))))
 '(org-use-speed-commands
   (lambda nil
     (and
      (looking-at org-outline-regexp)
      (looking-back "^**"))) nil nil "Customized with use-package org")
 '(package-archives
   (quote
    (("marmalade" . "https://marmalade-repo.org/packages/")
     ("melpa" . "https://melpa.org/packages/"))))
 '(package-selected-packages
   (quote
    (mexican-holidays holidays org-agenda undo-tree paradox restart-emacs dhall-mode ox-clip deft dockerfile-mode ox-gfm swiper-helm auth-sources plantuml-mode org-fstree esup package-build org-capture org-babel ox-texinfo gist helm-flx which-key spaceline pretty-mode visual-regexp-steroids ox-hugo adaptive-wrap yankpad smart-mode-line org-plus-contrib ob-cfengine3 org-journal ox-asciidoc org-jira ox-jira org-bullets ox-reveal lispy parinfer uniquify csv all-the-icons toc-org helm cider clojure-mode ido-completing-read+ writeroom-mode crosshairs ox-confluence ox-md inf-ruby ob-plantuml ob-ruby darktooth-theme kaolin-themes htmlize ag col-highlight nix-mode easy-hugo elvish-mode zen-mode racket-mode package-lint scala-mode go-mode wc-mode neotree applescript-mode ack magit clj-refactor yaml-mode visual-fill-column visible-mark use-package unfill typopunct smooth-scrolling smex smartparens rainbow-delimiters projectile markdown-mode magit-popup lua-mode keyfreq imenu-anywhere iedit ido-ubiquitous hl-sexp gruvbox-theme git-commit fish-mode exec-path-from-shell company clojure-mode-extra-font-locking clojure-cheatsheet aggressive-indent adoc-mode 4clojure)))
 '(paradox-github-token t)
 '(plantuml-jar-path "/usr/local/Cellar/plantuml/1.2019.9/libexec/plantuml.jar" t nil "Customized with use-package plantuml-mode")
 '(read-buffer-completion-ignore-case t)
 '(read-file-name-completion-ignore-case t)
 '(reb-re-syntax (quote string))
 '(recentf-max-menu-items 100 nil nil "Customized with use-package recentf")
 '(recentf-max-saved-items 100 nil nil "Customized with use-package recentf")
 '(show-trailing-whitespace nil)
 '(sml/replacer-regexp-list
   (quote
    (("^~/\\.emacs\\.d/elpa/" ":ELPA:")
     ("^~/\\.emacs\\.d/" ":ED:")
     ("^/sudo:.*:" ":SU:")
     ("^~/Documents/" ":Doc:")
     ("^:\\([^:]*\\):Documento?s/" ":\\1/Doc:")
     ("^~/Dropbox/" ":DB:")
     ("^:DB:org" ":Org:")
     ("^:DB:Personal/" ":P:")
     ("^:DB:Personal/writing/" ":Write:")
     ("^:P:devel/" ":Dev:")
     ("^:Write:learning-cfengine-3/learning-cfengine-3/" ":cf-learn:")
     ("^:Dev:go/src/github.com/elves/elvish/" ":elvish:")
     ("^:Dev:zzamboni.org/zzamboni.org/" ":zz.org:"))) nil nil "Customized with use-package smart-mode-line")
 '(sml/theme (quote dark) nil nil "Customized with use-package smart-mode-line")
 '(sp-base-key-bindings (quote paredit) nil nil "Customized with use-package smartparens")
 '(tab-width 2)
 '(tool-bar-mode nil)
 '(uniquify-after-kill-buffer-p t nil nil "Customized with use-package uniquify")
 '(uniquify-buffer-name-style (quote post-forward) nil (uniquify) "Customized with use-package uniquify")
 '(uniquify-strip-common-suffix t nil nil "Customized with use-package uniquify")
 '(use-package-always-defer t)
 '(use-package-always-ensure t)
 '(use-package-verbose nil)
 '(vr/engine (quote pcre2el) t nil "Use PCRE regular expressions"))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#282828" :foreground "#FDF4C1" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 160 :width normal :foundry "nil" :family "Inconsolata"))))
 '(col-highlight ((t (:background "#3c3836"))))
 '(fixed-pitch ((t (:family "Inconsolata"))))
 '(font-latex-sedate-face ((t (:inherit fixed-pitch :foreground "#a89984"))))
 '(font-lock-comment-face ((t (:inherit fixed-pitch :foreground "#7c6f64"))))
 '(font-lock-function-name-face ((t (:inherit fixed-pitch :foreground "#fabd2f"))))
 '(linum ((t (:background "#282828" :foreground "#504945" :height 140 :family "Inconsolata"))))
 '(markup-meta-face ((t (:foreground "gray40" :height 140 :family "Inconsolata"))))
 '(markup-title-0-face ((t (:inherit markup-gen-face :height 1.6))))
 '(markup-title-1-face ((t (:inherit markup-gen-face :height 1.5))))
 '(markup-title-2-face ((t (:inherit markup-gen-face :height 1.4))))
 '(markup-title-3-face ((t (:inherit markup-gen-face :weight bold :height 1.3))))
 '(markup-title-5-face ((t (:inherit markup-gen-face :underline t :height 1.1))))
 '(org-block ((t (:inherit fixed-pitch))))
 '(org-code ((t (:inherit (shadow fixed-pitch)))))
 '(org-document-info ((t (:foreground "dark orange"))))
 '(org-document-info-keyword ((t (:inherit (shadow fixed-pitch)))))
 '(org-document-title ((((class color) (min-colors 16777215)) (:foreground "#3FD7E5" :weight bold)) (((class color) (min-colors 255)) (:foreground "#00d7ff" :weight bold))))
 '(org-indent ((t (:inherit (org-hide fixed-pitch)))))
 '(org-level-1 ((((class color) (min-colors 16777215)) (:foreground "#FE8019")) (((class color) (min-colors 255)) (:foreground "#ff8700"))))
 '(org-level-2 ((((class color) (min-colors 16777215)) (:foreground "#B8BB26")) (((class color) (min-colors 255)) (:foreground "#afaf00"))))
 '(org-level-3 ((((class color) (min-colors 16777215)) (:foreground "#83A598")) (((class color) (min-colors 255)) (:foreground "#87afaf"))))
 '(org-level-4 ((((class color) (min-colors 16777215)) (:foreground "#FABD2F")) (((class color) (min-colors 255)) (:foreground "#ffaf00"))))
 '(org-level-5 ((((class color) (min-colors 16777215)) (:foreground "#427B58")) (((class color) (min-colors 255)) (:foreground "#5f8787"))))
 '(org-level-6 ((((class color) (min-colors 16777215)) (:foreground "#B8BB26")) (((class color) (min-colors 255)) (:foreground "#afaf00"))))
 '(org-level-7 ((((class color) (min-colors 16777215)) (:foreground "#FB4933")) (((class color) (min-colors 255)) (:foreground "#d75f5f"))))
 '(org-level-8 ((((class color) (min-colors 16777215)) (:foreground "#83A598")) (((class color) (min-colors 255)) (:foreground "#87afaf"))))
 '(org-link ((t (:foreground "royal blue" :underline t))))
 '(org-meta-line ((t (:inherit (font-lock-comment-face fixed-pitch)))))
 '(org-property-value ((t (:inherit fixed-pitch))) t)
 '(org-special-keyword ((t (:inherit (font-lock-comment-face fixed-pitch)))))
 '(org-table ((t (:inherit fixed-pitch :foreground "#83a598"))))
 '(org-tag ((t (:inherit (shadow fixed-pitch) :weight bold :height 0.8))))
 '(org-verbatim ((t (:inherit (shadow fixed-pitch)))))
 '(variable-pitch ((t (:weight light :height 180 :family "Source Sans Pro")))))
